import Discover from "@/components/Discover";
import Hero from "@/components/Hero";
import Hero2 from "@/components/Hero2";
import Moments from "@/components/Moments";
import Popular from "@/components/Popular";
import Special from "@/components/Special";
import Unique from "@/components/Unique";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Coffee Cafe</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Hero />
        <Unique />
        <Special />
        <Discover />
        <Popular />
        <Hero2 />
        <Moments />
      </main>
    </>
  );
}
